/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import com.vidiun.vdpfl.dummy.testcase1;
	
	import flash.display.Sprite;
	import com.vidiun.vdpfl.dummy.testcase2;
	import com.vidiun.vdpfl.DummySuit;
	
	public class FlexUnitCompilerApplication extends Sprite {
		private var com_vidiun_vdpfl_DummySuit_obj:com.vidiun.vdpfl.DummySuit;
		private var com_vidiun_vdpfl_dummy_testcase2_obj:com.vidiun.vdpfl.dummy.testcase2;
		
		
		private var com_vidiun_vdpfl_testcase1_obj:com.vidiun.vdpfl.dummy.testcase1;
	}
}